git:
  requireCleanWorkingDir: true
  requireBranch: main
  requireUpstream: true
  tag: true
  tagName: 'v${version}'
  tagAnnotation: 'v${version}'
  commit: false
  push: true

npm:
  publish: false

github:
  release: false

gitlab:
  release: false
